### ISSUE TITLE
Unable to create DB on first startup

### ISSUE THREAD

**Issue by Anaerin** [faulander/P4S#32]
Using the HEAD version, as apparently dev shouldn't be used. When trying to set up, I get the following error:
```
...
Creating p4s_nginx_1 ... done
 ===============================================================================================
 P4S - Migrate Database
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "app_user"
```

For reference, `.env.prod` looks like this:
```
DEBUG=0
SECRET_KEY=ANewKeyForPremieresForSonarrGoesHere
DJANGO_ALLOWED_HOSTS=*

# CHOOSE DATABASE BACKEND, POSTGRES IS STANDARD
SQL_ENGINE=django.db.backends.postgresql
#SQL_ENGINE=django.db.backends.mysql

# IF YOU'RE USING AN EXISTING DB, PLEASE CHANGE SETTINGS TO THE SETTINGS FOR YOUR EXISTING DB
SQL_DATABASE=app
SQL_USER=app_user
SQL_PASSWORD=app_user_password
SQL_HOST=db
SQL_PORT=5432
```
and `.env.prod.db` looks like this:
```
POSTGRES_USER=app_user
POSTGRES_PASSWORD=app_user_password
POSTGRES_DB=app
```
Which are virtually the defaults, aside from a new secret key.

**Comment by faulander** [comment]
Probably you already have db files on your volume.
If you used the settings i provided, try:
docker volumes rm p4s_postgres_data

and then rerun
