### ISSUE TITLE
Unhandled exception newshows.models.Setting.DoesNotExist: Setting matching query does not exist.                                                              

### ISSUE THREAD

**Issue by arogl** [faulander/P4S#4]
When I setup P4S, the settings.json was not applied correctly, so I manually added a record to the "newshows_setting" table using
insert into newshows_setting (id, page, profile_id, seasonfolders, addmonitored) values(1,0,1,1,1)

This managed to get the shows loaded and working, but now I have nothing in the newshows_setting table.

```
[2020-01-15 18:02:40,055] INFO:huey:Worker-1:Executing newshows.helpers.HelperUpdateTVMaze: c00dc9f0-c230-4527-8179-2c1828678188          
2020-01-15 18:02:40,055 INFO [huey:327] Executing newshows.helpers.HelperUpdateTVMaze: c00dc9f0-c230-4527-8179-2c1828678188               
[2020-01-15 18:02:40,057] ERROR:huey:Worker-1:Unhandled exception in task c00dc9f0-c230-4527-8179-2c1828678188.                           
Traceback (most recent call last):                                                                                                        
  File "C:\Python37\lib\site-packages\huey\api.py", line 345, in _execute                                                                 
    task_value = task.execute()                                                                                                           
  File "C:\Python37\lib\site-packages\huey\api.py", line 697, in execute                                                                  
    return func(*args, **kwargs)                                                                                                          
  File "C:\Python37\lib\site-packages\huey\contrib\djhuey\__init__.py", line 132, in inner                                                
    return fn(*args, **kwargs)                                                                                                            
  File "H:\Git\P4S\src\newshows\helpers.py", line 120, in HelperUpdateTVMaze                                                              
    settings = Setting.objects.get(id=1)                                                                                                  
  File "C:\Python37\lib\site-packages\django\db\models\manager.py", line 82, in manager_method                                            
    return getattr(self.get_queryset(), name)(*args, **kwargs)                                                                            
  File "C:\Python37\lib\site-packages\django\db\models\query.py", line 417, in get                                                        
    self.model._meta.object_name                                                                                                          
newshows.models.Setting.DoesNotExist: Setting matching query does not exist.                                                              
2020-01-15 18:02:40,057 ERROR [huey:360] Unhandled exception in task c00dc9f0-c230-4527-8179-2c1828678188.                                
Traceback (most recent call last):                                                                                                        
  File "C:\Python37\lib\site-packages\huey\api.py", line 345, in _execute                                                                 
    task_value = task.execute()                                                                                                           
  File "C:\Python37\lib\site-packages\huey\api.py", line 697, in execute                                                                  
    return func(*args, **kwargs)                                                                                                          
  File "C:\Python37\lib\site-packages\huey\contrib\djhuey\__init__.py", line 132, in inner                                                
    return fn(*args, **kwargs)                                                                                                            
  File "H:\Git\P4S\src\newshows\helpers.py", line 120, in HelperUpdateTVMaze                                                              
    settings = Setting.objects.get(id=1)                                                                                                  
  File "C:\Python37\lib\site-packages\django\db\models\manager.py", line 82, in manager_method                                            
    return getattr(self.get_queryset(), name)(*args, **kwargs)                                                                            
  File "C:\Python37\lib\site-packages\django\db\models\query.py", line 417, in get                                                        
    self.model._meta.object_name                                                                                                          
newshows.models.Setting.DoesNotExist: Setting matching query does not exist.                                                              
```

**Comment by faulander** [comment]
Can you try to load the fixtures once again with:
`python manage.py loaddata settings.json`

it states exactly, that the settings aren't correct here:
 File "H:\Git\P4S\src\newshows\helpers.py", line 120, in HelperUpdateTVMaze                                                              
    settings = Setting.objects.get(id=1)             

If you want to check the db directly, install DB Browser. It handles SQLite DB's very well.

**Comment by arogl** [comment]
That fixed it.

Thanks for the command.
